language: python

matrix:
  fast_finish: true
  include:
    - language: python
      os: linux
      env:
        - PYTHON_VERSION="3.7"
    - language: python
      os: linux
      env:
        - PYTHON_VERSION="3.7"

steps:
      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: 3.7

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel

      - uses: actions/checkout@v2
        name: Checkout repository

      - name: Build wheels for CPython (macOS)
        if: startsWith(matrix.os, 'macos')
        run: |
          brew config
          brew install gcc@9
          python -m cibuildwheel --output-dir dist
        env:
          CIBW_BUILD: "cp3?-*"
          CIBW_SKIP: "cp35-* cp39-*"
           # TODO: make it work for 10.9 (required libstdc++.dylib and libgomp.dylib from gcc compiled for 10.15)
          MACOSX_DEPLOYMENT_TARGET: 10.15
          # use gcc instead of clang
          CC: /usr/local/bin/gcc-9
          CXX: /usr/local/bin/g++-9

      - name: Build wheels for CPython (Linux and Windows)
        if: startsWith(matrix.os, 'macos') == false
        run: |
          python -m cibuildwheel --output-dir dist
        env:
         
          CIBW_BUILD: "cp3?-*x86_64 cp3?-*win_amd64"
          CIBW_SKIP: "cp35-* cp39-*"
          # numba is a requirement and only has wheels for manylinux2014
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
          

      - uses: actions/upload-artifact@v2
        name: Upload wheels
        with:
          name: wheels
          path: ./dist/*.whl
install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - echo ". $HOME/miniconda/etc/profile.d/conda.sh" >> $HOME/.bashrc
  - source $HOME/.bashrc
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda update -q conda
  - conda info -a
  - conda create -n naparienv -c conda-forge python=$PYTHON_VERSION
  - conda activate naparienv

  
script:
  - conda activate naparienv
  - python setup.py install
