language: python
python:
  - PYTHON_VERSION="3.8"
  - PYTHON_VERSION="3.9"
install:
  - conda create -n NapariTrack python=$PYTHON_VERSION
  - conda activate NapariTrack
  
script:
  - conda activate NapariTrack
  - python setup.py install
  

